# Generated by Django 5.2.14 on 2026-05-06 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('narration', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InternalLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=20)),
                ('reconciliation_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('bank_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance_app.bankstatement')),
                ('ledger_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance_app.internalledger')),
            ],
        ),
    ]
